/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desafioindividual;

/**
 *
 * @author user
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        titlo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        ValorMensalDeposito = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        QuantidadeMeses = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Calcular = new javax.swing.JButton();
        ValorInicialDeposito = new javax.swing.JTextField();
        Resultado = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador de Investimentos");
        setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(0, 153, 153));
        setLocation(new java.awt.Point(180, 10));
        setMaximumSize(new java.awt.Dimension(666, 510));
        setMinimumSize(new java.awt.Dimension(666, 510));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 250, 20));

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("E ABRA SUA CONTA COM A GENTE");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 340, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Garantimos 5% de bonus para cada deposito realizado");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 360, -1));

        titlo.setFont(new java.awt.Font("Dubai", 1, 22)); // NOI18N
        titlo.setForeground(new java.awt.Color(255, 255, 255));
        titlo.setText("SIMULE SEU INVESTIMENTO ");
        titlo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(titlo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 310, 60));

        jLabel6.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Quantidades de mesês:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 250, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 250, 10));

        ValorMensalDeposito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ValorMensalDeposito.setForeground(new java.awt.Color(0, 153, 153));
        ValorMensalDeposito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ValorMensalDeposito.setBorder(null);
        ValorMensalDeposito.setOpaque(false);
        jPanel1.add(ValorMensalDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 250, 30));

        jLabel9.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Temos a melhor proposta de ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("investimentos para você");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, -1, -1));

        QuantidadeMeses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        QuantidadeMeses.setForeground(new java.awt.Color(0, 153, 153));
        QuantidadeMeses.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        QuantidadeMeses.setBorder(null);
        QuantidadeMeses.setOpaque(false);
        jPanel1.add(QuantidadeMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 250, 30));

        jLabel5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Valor Mensal: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 90, 50));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desafioindividual/ixo.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 250, 230));

        jLabel2.setBackground(java.awt.SystemColor.activeCaption);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/desafioindividual/direitaJava.png"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(240, 240, 240), 3, true));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 510));

        jLabel8.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Valor deposito inicial: ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        Calcular.setBackground(new java.awt.Color(255, 255, 255));
        Calcular.setFont(new java.awt.Font("Lucida Console", 0, 14)); // NOI18N
        Calcular.setForeground(new java.awt.Color(153, 153, 153));
        Calcular.setText("Calcular");
        Calcular.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 2, true));
        Calcular.setBorderPainted(false);
        Calcular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Calcular.setOpaque(false);
        Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularActionPerformed(evt);
            }
        });
        jPanel1.add(Calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 120, 30));

        ValorInicialDeposito.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ValorInicialDeposito.setForeground(new java.awt.Color(0, 153, 153));
        ValorInicialDeposito.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ValorInicialDeposito.setBorder(null);
        jPanel1.add(ValorInicialDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 120, 250, 30));

        Resultado.setFont(new java.awt.Font("Dubai", 1, 48)); // NOI18N
        Resultado.setForeground(new java.awt.Color(153, 153, 153));
        Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Resultado.setText("00.00");
        Resultado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 220, 70));

        jLabel12.setFont(new java.awt.Font("Dubai", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 153));
        jLabel12.setText("R$");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, -1, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 220, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularActionPerformed
        // TODO add your handling code here:
        String depositoInicial = ValorInicialDeposito.getText();
        String depositoMensal = ValorMensalDeposito.getText();
        String qtdmes = QuantidadeMeses.getText();
        Double ValorBonusMensal = Double.parseDouble(qtdmes) * Double.parseDouble(depositoMensal)*0.05;
        
        Double valorTotalDosMeses = ( Double.parseDouble(qtdmes) * Double.parseDouble(depositoMensal)) + ValorBonusMensal;    
    
        Double ValorBonusEntrada =  Double.parseDouble(depositoInicial)*0.05; 
        Double ValorTotalEntrada =  Double.parseDouble(depositoInicial)+ValorBonusEntrada; 
     
        Double ValorTotal = ValorTotalEntrada+ valorTotalDosMeses ;
     
        Resultado.setText(ValorTotal.toString());
    }//GEN-LAST:event_CalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calcular;
    private javax.swing.JTextField QuantidadeMeses;
    private javax.swing.JLabel Resultado;
    private javax.swing.JTextField ValorInicialDeposito;
    private javax.swing.JTextField ValorMensalDeposito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel titlo;
    // End of variables declaration//GEN-END:variables
}
